{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "An unexpected error occurred with file adjunct_island.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\adjunct_island.jsonl'\n",
      "An unexpected error occurred with file anaphor_gender_agreement.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\anaphor_gender_agreement.jsonl'\n",
      "An unexpected error occurred with file anaphor_number_agreement.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\anaphor_number_agreement.jsonl'\n",
      "An unexpected error occurred with file animate_subject_passive.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\animate_subject_passive.jsonl'\n",
      "An unexpected error occurred with file animate_subject_trans.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\animate_subject_trans.jsonl'\n",
      "An unexpected error occurred with file causative.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\causative.jsonl'\n",
      "An unexpected error occurred with file complex_NP_island.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\complex_NP_island.jsonl'\n",
      "An unexpected error occurred with file coordinate_structure_constraint_complex_left_branch.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\coordinate_structure_constraint_complex_left_branch.jsonl'\n",
      "An unexpected error occurred with file coordinate_structure_constraint_object_extraction.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\coordinate_structure_constraint_object_extraction.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_1.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_2.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_irregular_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_irregular_1.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_irregular_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_irregular_2.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_with_adjective_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_with_adjective_1.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_with_adj_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_with_adj_2.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_with_adj_irregular_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_with_adj_irregular_1.jsonl'\n",
      "An unexpected error occurred with file determiner_noun_agreement_with_adj_irregular_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\determiner_noun_agreement_with_adj_irregular_2.jsonl'\n",
      "An unexpected error occurred with file distractor_agreement_relational_noun.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\distractor_agreement_relational_noun.jsonl'\n",
      "An unexpected error occurred with file distractor_agreement_relative_clause.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\distractor_agreement_relative_clause.jsonl'\n",
      "An unexpected error occurred with file drop_argument.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\drop_argument.jsonl'\n",
      "An unexpected error occurred with file ellipsis_n_bar_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\ellipsis_n_bar_1.jsonl'\n",
      "An unexpected error occurred with file ellipsis_n_bar_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\ellipsis_n_bar_2.jsonl'\n",
      "An unexpected error occurred with file existential_there_object_raising.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\existential_there_object_raising.jsonl'\n",
      "An unexpected error occurred with file existential_there_quantifiers_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\existential_there_quantifiers_1.jsonl'\n",
      "An unexpected error occurred with file existential_there_quantifiers_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\existential_there_quantifiers_2.jsonl'\n",
      "An unexpected error occurred with file existential_there_subject_raising.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\existential_there_subject_raising.jsonl'\n",
      "An unexpected error occurred with file expletive_it_object_raising.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\expletive_it_object_raising.jsonl'\n",
      "An unexpected error occurred with file inchoative.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\inchoative.jsonl'\n",
      "An unexpected error occurred with file intransitive.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\intransitive.jsonl'\n",
      "An unexpected error occurred with file irregular_past_participle_adjectives.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\irregular_past_participle_adjectives.jsonl'\n",
      "An unexpected error occurred with file irregular_past_participle_verbs.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\irregular_past_participle_verbs.jsonl'\n",
      "An unexpected error occurred with file irregular_plural_subject_verb_agreement_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\irregular_plural_subject_verb_agreement_1.jsonl'\n",
      "An unexpected error occurred with file irregular_plural_subject_verb_agreement_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\irregular_plural_subject_verb_agreement_2.jsonl'\n",
      "An unexpected error occurred with file left_branch_island_echo_question.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\left_branch_island_echo_question.jsonl'\n",
      "An unexpected error occurred with file left_branch_island_simple_question.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\left_branch_island_simple_question.jsonl'\n",
      "An unexpected error occurred with file matrix_question_npi_licensor_present.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\matrix_question_npi_licensor_present.jsonl'\n",
      "An unexpected error occurred with file npi_present_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\npi_present_1.jsonl'\n",
      "An unexpected error occurred with file npi_present_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\npi_present_2.jsonl'\n",
      "An unexpected error occurred with file only_npi_licensor_present.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\only_npi_licensor_present.jsonl'\n",
      "An unexpected error occurred with file only_npi_scope.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\only_npi_scope.jsonl'\n",
      "An unexpected error occurred with file passive_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\passive_1.jsonl'\n",
      "An unexpected error occurred with file passive_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\passive_2.jsonl'\n",
      "An unexpected error occurred with file principle_A_case_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_case_1.jsonl'\n",
      "An unexpected error occurred with file principle_A_case_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_case_2.jsonl'\n",
      "An unexpected error occurred with file principle_A_c_command.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_c_command.jsonl'\n",
      "An unexpected error occurred with file principle_A_domain_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_domain_1.jsonl'\n",
      "An unexpected error occurred with file principle_A_domain_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_domain_2.jsonl'\n",
      "An unexpected error occurred with file principle_A_domain_3.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_domain_3.jsonl'\n",
      "An unexpected error occurred with file principle_A_reconstruction.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\principle_A_reconstruction.jsonl'\n",
      "An unexpected error occurred with file regular_plural_subject_verb_agreement_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\regular_plural_subject_verb_agreement_1.jsonl'\n",
      "An unexpected error occurred with file regular_plural_subject_verb_agreement_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\regular_plural_subject_verb_agreement_2.jsonl'\n",
      "An unexpected error occurred with file sentential_negation_npi_licensor_present.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\sentential_negation_npi_licensor_present.jsonl'\n",
      "An unexpected error occurred with file sentential_negation_npi_scope.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\sentential_negation_npi_scope.jsonl'\n",
      "An unexpected error occurred with file sentential_subject_island.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\sentential_subject_island.jsonl'\n",
      "An unexpected error occurred with file superlative_quantifiers_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\superlative_quantifiers_1.jsonl'\n",
      "An unexpected error occurred with file superlative_quantifiers_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\superlative_quantifiers_2.jsonl'\n",
      "An unexpected error occurred with file tough_vs_raising_1.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\tough_vs_raising_1.jsonl'\n",
      "An unexpected error occurred with file tough_vs_raising_2.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\tough_vs_raising_2.jsonl'\n",
      "An unexpected error occurred with file transitive.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\transitive.jsonl'\n",
      "An unexpected error occurred with file wh_island.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_island.jsonl'\n",
      "An unexpected error occurred with file wh_questions_object_gap.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_questions_object_gap.jsonl'\n",
      "An unexpected error occurred with file wh_questions_subject_gap.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_questions_subject_gap.jsonl'\n",
      "An unexpected error occurred with file wh_questions_subject_gap_long_distance.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_questions_subject_gap_long_distance.jsonl'\n",
      "An unexpected error occurred with file wh_vs_that_no_gap.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_vs_that_no_gap.jsonl'\n",
      "An unexpected error occurred with file wh_vs_that_no_gap_long_distance.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_vs_that_no_gap_long_distance.jsonl'\n",
      "An unexpected error occurred with file wh_vs_that_with_gap.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_vs_that_with_gap.jsonl'\n",
      "An unexpected error occurred with file wh_vs_that_with_gap_long_distance.jsonl: [WinError 32] The process cannot access the file because it is being used by another process: './blimp_data_raw\\\\wh_vs_that_with_gap_long_distance.jsonl'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import json\n",
    "import shutil\n",
    "\n",
    "# Directory where the JSON files are stored\n",
    "source_directory = './blimp_data_raw'\n",
    "\n",
    "# Directories to move files into based on conditions\n",
    "dir1 = './sorted_data/morp'\n",
    "dir2 = './sorted_data/sem'\n",
    "dir3 = './sorted_data/syn'\n",
    "dir4 = './sorted_data/synsem'\n",
    "\n",
    "# Create directories if they do not exist\n",
    "for directory in [dir1, dir2, dir3, dir4]:\n",
    "    os.makedirs(directory, exist_ok=True)\n",
    "\n",
    "# The name of the field to sort by\n",
    "field_name = 'field'\n",
    "\n",
    "# Function to categorize the file based on the field value\n",
    "def categorize_file(value):\n",
    "    if value == 'morphology':\n",
    "        return dir1\n",
    "    elif value == 'semantics':\n",
    "        return dir2\n",
    "    elif value == 'syntax':\n",
    "        return dir3\n",
    "    else:\n",
    "        return dir4\n",
    "\n",
    "# Process each JSON file in the source directory\n",
    "for filename in os.listdir(source_directory):\n",
    "    file_path = os.path.join(source_directory, filename)\n",
    "    if filename.endswith('.jsonl'):\n",
    "        with open(file_path, 'r') as file:\n",
    "            try:\n",
    "                first_line = file.readline()  # Read the first line only\n",
    "                data = json.loads(first_line)  # Parse the first JSON object\n",
    "                sort_value = data[field_name]\n",
    "                target_directory = categorize_file(sort_value)\n",
    "                shutil.move(file_path, os.path.join(target_directory, filename))\n",
    "            except json.JSONDecodeError:\n",
    "                print(f\"Error decoding JSON in file {filename}. Please check the file format.\")\n",
    "            except KeyError:\n",
    "                print(f\"Field {field_name} not found in file {filename}. Please check the field name.\")\n",
    "            except Exception as e:\n",
    "                print(f\"An unexpected error occurred with file {filename}: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
